apiVersion: v1
kind: Pod
metadata:
  name: test-cinder
spec:
  containers:
  - image: nginx
    name: test-cinder-container
    volumeMounts:
    - mountPath: /test-cinder
      name: test-volume
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: test-volume
    hostPath:
      path: /var/run/docker.sock
