apiVersion: v1
kind: Pod
metadata:
  name: p
spec:
  containers:
  - name: avinesh
    image: nginx
    securityContext:
      privileged: true
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
